config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :daily_reports do
	get 'payoutsreport', on: :collection
	resources :payouts, :deposits, :smowithdrawals
  end

  resources :transactions do
	get 'report', on: :collection
	get 'toggle_flagged', :on => :member
  end

  namespace :api, defaults: {format: 'json'} do
	namespace :v1 do
		resources :entry_types 
	end
  end

end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
	def create
		@daily_report = DailyReport.find(params[:daily_report_id])
		@deposit = @daily_report.transactions.create(deposit_params)
		redirect_to daily_report_deposits_path(@daily_report)
	end

	def index
		@entry_category = EntryCategory.find_by(category: 'Daily Deposit')
		@daily_report = DailyReport.find(params[:daily_report_id])
	end

	def edit
		@daily_report = DailyReport.find(params[:daily_report_id])
		@deposit = @daily_report.transactions.find(params[:id])
	end

	def update
		@daily_report = DailyReport.find(params[:daily_report_id])
		@deposit = @daily_report.transactions.find(params[:id])

		if @deposit.update(deposit_params)
			redirect_to daily_report_deposits_path(@daily_report)
		else
			render 'edit'
		end
	end

	def destroy
		@daily_report = DailyReport.find(params[:daily_report_id])
		@deposit = @daily_report.transactions.find(params[:id])
		@deposit.destroy
		redirect_to daily_report_deposits_path(@daily_report)
	end
	
	private
		def deposit_params
			params.require(:deposit).permit(:accounting_date, :transaction_date, :description, :entry_type_id, :entry_category_id, :amount)
		end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= form_for @deposit, :as => :deposit, :url => daily_report_deposits_path(@daily_report, @deposit) do |f| %>
	<% if @deposit.errors.any? %>
                <div id="error_explanation">
                        <h2>
                                <%= pluralize(@deposit.errors.count, "error") %> prohibited this 
                                deposit being saved:
                        </h2>
                        <ul>
                                <% @deposit.errors.full_messages.each do |msg| %>
                                        <li><%= msg %></li>
                                <% end %>
                        </ul>
                </div>
        <% end %>

        <p>
                <%= f.label "Deposit Date" %><br>
                <%= f.date_select :transaction_date, default: Date.today %>
        </p>

        <p>
                <%= f.label :description %><br>
                <%= f.text_field :description %>
        </p>

        <p>
                <%= f.label :amount %><br>
                <%= f.number_field :amount, :class => 'text_field', :step => 'any' %>
        </p>

	<%= f.hidden_field :entry_type_id, :value => @entry_category.entry_type_id %>
	<%= f.hidden_field :entry_category_id, :value => @entry_category.id %>
	<%= f.hidden_field :accounting_date, :value => @daily_report.date %>	

        <p>
                <%= f.submit %>
        </p>
<% end %>

app/views/deposits/index.html.erb
<h1>Deposits</h1>

<table>
	<tr>
		<th>Deposit Date</th>
		<th>Description</th>
		<th>Amount</th>
		<th colspan="1"></th>
	</tr>
	
	<% @daily_report.transactions.joins(:entry_category).where(entry_categories: { category: 'Daily Deposit' }).each do |deposit| %>
		<tr>
			<td><%= deposit.transaction_date %></td>
			<td><%= deposit.description %></td>
			<td><%= number_to_currency(deposit.amount) %></td>
			<td><%= link_to 'Delete', daily_report_deposit_path(deposit.daily_report, deposit),
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<h2>Add a deposit:</h2>

<% @deposit = @daily_report.transactions.build %>
<%= render 'form' %>

<p>
		<%= link_to 'Back', daily_reports_path %>
</p>		