config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :daily_reports do
	get 'payoutsreport', on: :collection
	resources :payouts, :deposits, :smowithdrawals
  end

  resources :transactions do
	get 'report', on: :collection
	get 'toggle_flagged', :on => :member
  end

  namespace :api, defaults: {format: 'json'} do
	namespace :v1 do
		resources :entry_types 
	end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def index
		@from_date_is_null = true
		@to_date_is_null = true
		@description_is_null = true
		@category_is_null = true
		
		if (params[:from_date] && params[:from_date] != "")
			@from_date_is_null = false
			from_date = params[:from_date]
		else
			from_date = 2.weeks.ago
		end

		if (params[:to_date] && params[:to_date] != "")
			@to_date_is_null = false
			to_date = params[:to_date]
		else
			to_date = Date.today
		end

		if (params[:description] && params[:description] != "*")
			@description_is_null = false
			description = params[:description]
		else
			description = nil
		end

		if (params[:category] && params[:category] != "*")
			@category_is_null = false
			category = params[:category]
		else
			category = nil
		end

		@credit_transactions_filtered = Transaction.FilterCredit().FilterByDescription(description).FilterByCategory(category)
		@debit_transactions_filtered = Transaction.FilterDebit().FilterByDescription(description).FilterByCategory(category)

		@credit_transactions = @credit_transactions_filtered.FilterByTDate(from_date, to_date).order('transaction_date ASC')
		@debit_transactions = @debit_transactions_filtered.FilterByTDate(from_date, to_date).order('transaction_date ASC') 
		
		@old_credit_transactions = @credit_transactions_filtered.where("transaction_date < ?", from_date)
		@old_debit_transactions = @debit_transactions_filtered.where("transaction_date < ?", from_date)
	end

	def new
		@transaction = Transaction.new
	end

	def edit
		@transaction = Transaction.find(params[:id])
	end

	def create
		@transaction = Transaction.new(transaction_params)
		
		if @transaction.save
			redirect_to transactions_path
		else
			render 'new'
		end
	end

	def update
		@transaction = Transaction.find(params[:id])
		
		if @transaction.update(transaction_params)
			redirect_to transactions_path
		else
			render 'edit'
		end
	end
	
	def destroy
		@transaction = Transaction.find(params[:id])
		@transaction.destroy

		redirect_to transactions_path
	end

	def report
		@from_date_is_null = true
		@to_date_is_null = true

		if (params[:from_date])
			@from_date_is_null = false
			from_date = params[:from_date]
		else
			from_date = 1.month.ago
		end

		
		if (params[:to_date])
			@to_date_is_null = false
			to_date = params[:to_date]
		else
			to_date = Date.today
		end

		@credit_transactions = Transaction.FilterCredit.FilterByADate(from_date, to_date)
		@debit_transactions = Transaction.FilterDebit.FilterByADate(from_date, to_date)

		@credit_transaction_groups = @credit_transactions.joins(:entry_category).select("category, amount").group(:category).order('category ASC').sum(:amount)
		@debit_transaction_groups = @debit_transactions.joins(:entry_category).select("category, amount").group(:category).order('category ASC').sum(:amount)

		@sum_credits = @credit_transactions.sum(:amount)
		@sum_debits = @debit_transactions.sum(:amount)
	end

	def toggle_flagged
		@transaction = Transaction.find(params[:id])
		@transaction.toggle!(:flagged)

		respond_to do |format|
			format.js {render inline: "location.reload();" }
		end
	end

	private
		def transaction_params
			params.require(:transaction).permit(:accounting_date, :transaction_date, :description, :entry_type_id, :entry_category_id, :amount)
		end	
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for @transaction do |f| %>
	
	<% if @transaction.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@transaction.errors.count, "error") %> prohibited this 
				transaction from being saved:
			</h2>
			<ul>
				<% @transaction.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>
	<% end %>

	<p>
		<%= f.label :accounting_date %><br>
		<%= f.date_select :accounting_date, default: Date.today %>
	</p>

	<p>
		<%= f.label :transaction_date %><br>
		<%= f.date_select :transaction_date, default: Date.today %>
	</p>

	<p>
		<%= f.label :entry_type_id %><br>
		<%= f.collection_select :entry_type_id, EntryType.all, :id, :entry_type %>	
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>

	<p>
		<%= f.label :entry_category_id %><br>
		<%= f.collection_select :entry_category_id, EntryCategory.all, :id, :category %>
	</p>

	<p>
		<%= f.label :amount %><br>
		<%= f.number_field :amount, :class => 'text_field', :step => 'any' %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<%= stylesheet_link_tag "transactions" %>

<h1>List of transactions</h1>

<%= link_to 'New Transaction', new_transaction_path %>

<%= form_tag transactions_path, :method => 'get' do %>
	<p>
		<%= label_tag "From Date: " %>

		<% if @from_date_is_null == true %>
			<%= date_field_tag :from_date, 2.weeks.ago.to_date %>
		<% else %>
			<%= date_field_tag :from_date, params[:from_date] %>
		<% end %>

		
		<%= label_tag "To Date: " %>

		<% if @to_date_is_null == true %>
			<%= date_field_tag :to_date, Date.today %>
		<% else %>
			<%= date_field_tag :to_date, params[:to_date] %>
		<% end %>


		<%= label_tag "Description: " %>

		<% if (@description_is_null == true || params[:description] == "") %>
			<%= text_field_tag :description, "*" %>
		<% else %>
			<%= text_field_tag :description, params[:description] %>
		<% end %>
		
		<%= label_tag "Category: " %>
		
		<% if (@category_is_null == true || params[:category] == "") %>
			<%= text_field_tag :category, "*" %>
		<% else %>
			<%= text_field_tag :category, params[:category] %>
		<% end %>

		<%= submit_tag "Filter", :name => nil %>
	</p>
<% end %>

<table class="transactions">
	<tr><td><h2>Credits</h2></td></tr>

	<tr>
		<th>Accounting Date</th>
		<th>Transaction Date</th>
		<th>Description</th>
		<th>Category</th>
		<th>Amount</th>
		<th colspan="4"></th>
	</tr>

	<tr>
		<td>N/A</td>
		<td>N/A</td>
		<td>Balance Fwd</td>
		<td>Balance Fwd</td>
		<td class="amount"><%= number_to_currency(@old_credit_transactions.sum(:amount)) %></td>
	</tr>

	<% @credit_transactions.each do |transaction| %>

		<tr>
			<td><%= transaction.accounting_date =%></td>
			<td><%= transaction.transaction_date =%></td>
			<td <% if transaction.flagged %> bgcolor="lightcoral" <%end%>><%= transaction.description =%></td>
			<td <% if transaction.flagged %> bgcolor="lightcoral" <%end%>><%= transaction.entry_category.category =%></td>
			<td <% if transaction.flagged %> bgcolor="lightcoral" <%end%> class="amount"><%= number_to_currency(transaction.amount) =%></td>
			<td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
			<td><%= link_to 'Delete', transaction_path(transaction),
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>	
			<td><% if !transaction.flagged %>
				<%= link_to 'Flag', 
				    toggle_flagged_transaction_path(transaction.id),
			 	    :remote => true %>
		            <% else %>
				<%= link_to 'Un-Flag', 
				    toggle_flagged_transaction_path(transaction.id),
			 	    :remote => true %>
			    <% end %>
			</td>
		</tr>
	<% end %>

	<tr>
		<td colspan="3"></th>
		<td><b>Total Credits</b></th>
		<td class="amount"><b><%= number_to_currency(@credit_transactions.sum(:amount) + @old_credit_transactions.sum(:amount)) %></b></th>
	</tr>

	<tr><td><h2>Debits</h2></td></tr>

        <tr>
                <th>Accounting Date</th>
                <th>Transaction Date</th>
                <th>Description</th>
                <th>Category</th>
                <th>Amount</th>
                <th colspan="4"></th>
        </tr>

	<tr>
		<td>N/A</td>
		<td>N/A</td>
		<td>Balance Fwd</td>
		<td>Balance Fwd</td>
		<td class="amount"><%= number_to_currency(@old_debit_transactions.sum(:amount)) %></td>
	</tr>

        <% @debit_transactions.each do |transaction| %>
                <tr>
                        <td><%= transaction.accounting_date =%></td>
                        <td><%= transaction.transaction_date =%></td>
                        <td <% if transaction.flagged %> bgcolor="lightcoral" <%end%>><%= transaction.description =%></td>
                        <td <% if transaction.flagged %> bgcolor="lightcoral" <%end%>><%= transaction.entry_category.category =%></td>
                        <td <% if transaction.flagged %> bgcolor="lightcoral" <%end%> class="amount"><%= number_to_currency(transaction.amount) =%></td>
                        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
                        <td><%= link_to 'Delete', transaction_path(transaction),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>      
			<td><% if !transaction.flagged %>
				<%= link_to 'Flag', 
				    toggle_flagged_transaction_path(transaction.id),
			 	    :remote => true %>
		            <% else %>
				<%= link_to 'Un-Flag', 
				    toggle_flagged_transaction_path(transaction.id),
			 	    :remote => true %>
			    <% end %>
			</td>
                </tr>
        <% end %>

	<tr>
		<td colspan="3"></th>
		<td><b>Total Debits</b></th>
		<td class="amount"><b><%= number_to_currency(@debit_transactions.sum(:amount) + @old_debit_transactions.sum(:amount)) %></b></th>
	</tr>

	<tr>
		<td colspan="3"></td>
		<td><b>Net Balance</b></td>
		<td class="amount"><b><%= number_to_currency((@credit_transactions.sum(:amount) + @old_credit_transactions.sum(:amount)) -
			   		      (@debit_transactions.sum(:amount) + @old_debit_transactions.sum(:amount))) %></b></td>
	</tr>
</table>

<%= link_to 'Back to home', root_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

<%= javascript_include_tag "/javascripts/dynamic_categories" %>

app/views/transactions/report.html.erb
<%= stylesheet_link_tag "transactions" %>

<h1> Bank Transactions Summary </h1>

<%= form_tag report_transactions_path, :method => 'get' do %>
	<p>
		<%= label_tag "From Date: " %>
		
		<% if @from_date_is_null == true %>
			<%= date_field_tag :from_date, 1.month.ago.to_date %>
		<% else %>
			<%= date_field_tag :from_date, params[:from_date] %>
		<% end %>

		<%= label_tag "To Date: " %>
		
		<% if @to_date_is_null == true %>
			<%= date_field_tag :to_date, Date.today %>
		<% else %>
			<%= date_field_tag :to_date, params[:to_date] %>
		<% end %>

		<%= submit_tag "Report", :name => nil %>
<% end %>

<table>
	<tr><td><h2>Credits</h2></td></tr>

	<tr>
		<th>Category</th>
		<th>Amount</th>
	</tr>

	<% @credit_transaction_groups.each do |transaction_group| %>
		<tr>
			<td><%= transaction_group[0] %></td>
			<td align="right"><%= number_to_currency(transaction_group[1]) %></td>
		</tr>
	<% end %>
	
	<tr>
		<td><b>Total</b></td>
		<td align="right"><b><%= number_to_currency(@sum_credits) %></b></td>
	</tr>

	<tr><td><h2>Debits</h2></td></tr>

	<tr>
		<th>Category</th>
		<th>Amount</th>
	</tr>

	<% @debit_transaction_groups.each do |transaction_group| %>
		<tr>
			<td><%= transaction_group[0] %></td>
			<td align="right"><%= number_to_currency(transaction_group[1]) %></td>
		</tr>
	<% end %>
	
	<tr>
		<td><b>Total</b></td>
		<td align="right"><b><%= number_to_currency(@sum_debits) %></b></td>
	</tr>

	<tr>
		<td><b>Difference</b></td>
		<td align="right"><b><u><%= number_to_currency(@sum_credits - @sum_debits) %></u></b></td>
	</tr>	

</table>

<br>

<%= link_to 'Back to home', root_path %>