config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :daily_reports do
	get 'payoutsreport', on: :collection
	resources :payouts, :deposits, :smowithdrawals
  end

  resources :transactions do
	get 'report', on: :collection
	get 'toggle_flagged', :on => :member
  end

  namespace :api, defaults: {format: 'json'} do
	namespace :v1 do
		resources :entry_types 
	end
  end

end

app/models/payout.rb
class Payout < ActiveRecord::Base
  belongs_to :daily_report
  belongs_to :payout_category
  validates :description, presence: true, length: { minimum: 3 }
end

app/controllers/payouts_controller.rb
class PayoutsController < ApplicationController
	def create
		@daily_report = DailyReport.find(params[:daily_report_id])
		@payout = @daily_report.payouts.create(payout_params)
		redirect_to daily_report_payouts_path(@daily_report)
	end

	def index
		@daily_report = DailyReport.find(params[:daily_report_id])
	end

	def edit
		@daily_report = DailyReport.find(params[:daily_report_id])
		@payout = @daily_report.payouts.find(params[:id])
	end

	def update
		@daily_report = DailyReport.find(params[:daily_report_id])
		@payout = @daily_report.payouts.find(params[:id])

	 	if @payout.update(payout_params)
			redirect_to daily_report_payouts_path(@daily_report)
		else
			render 'edit'
		end
	end

	def destroy
		@daily_report = DailyReport.find(params[:daily_report_id])
		@payout = @daily_report.payouts.find(params[:id])
		@payout.destroy
		redirect_to daily_report_payouts_path(@daily_report)		
	end


	private
		def payout_params
			params.require(:payout).permit(:description, :amount, :payout_category_id)
		end
end

app/helpers/payouts_helper.rb
module PayoutsHelper
end

app/views/payouts/_form.html.erb
<%= form_for([@daily_report,@payout]) do |f| %>

	<% if @payout.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@payout.errors.count, "error") %> prohibited this payout from being saved:
			</h2>
			<ul>
				<%= @payout.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>

	<p>
		<%= f.label :category %><br>
		<%= f.collection_select :payout_category_id, PayoutCategory.all, :id, :pcategory %>
	</p>

	<p>
		<%= f.label :amount %><br>
		<%= f.number_field :amount, :class => 'text_field', :step => 'any' %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/payouts/edit.html.erb
<h1>Edit payout</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_report_payouts_path(@daily_report) %>

app/views/payouts/index.html.erb
<h1>Payouts</h1>

<table>
	<tr>
		<th>Description</th>
		<th>Category</th>
		<th>Amount</th>
		<th colspan="2"></th>
	</tr>

	
	<% @daily_report.payouts.each do |payout| %>
		<tr>
			<td><%= payout.description %></td>
			<td><%= payout.payout_category.pcategory%></td>
			<td><%= number_to_currency(payout.amount) %></td>
			<td><%= link_to 'Edit', edit_daily_report_payout_path(payout.daily_report, payout) %></td>
			<td><%= link_to 'Delete', daily_report_payout_path(payout.daily_report, payout), 
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<h2>Add a payout:</h2>

<% @payout = @daily_report.payouts.build %>
<%= render 'form' %>

<p>
	<%= link_to 'Back', daily_reports_path %>	
</p>