config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :daily_reports do
	get 'payoutsreport', on: :collection
	resources :payouts, :deposits, :smowithdrawals
  end

  resources :transactions do
	get 'report', on: :collection
	get 'toggle_flagged', :on => :member
  end

  namespace :api, defaults: {format: 'json'} do
	namespace :v1 do
		resources :entry_types 
	end
  end

end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
	has_many :payouts, dependent: :destroy
	has_many :transactions, dependent: :destroy
	validates :date, :grocery, :fuel, :gift_cards, :credit, :debit, :cash, :commission, :cash_counted, :commission, :cash_counted, presence: true
	validates :date, uniqueness: true	
	
	def self.FilterByDate(from_date, to_date)
		where("date >= ? AND date <= ?", from_date, to_date)
	end
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
	def index

		@from_date_is_null = true
		@to_date_is_null = true

		if (params[:from_date])
			@from_date_is_null = false
			from_date = params[:from_date]
		else
			from_date = 2.weeks.ago
		end
		
		if (params[:to_date])
			@to_date_is_null = false
			to_date = params[:to_date]
		else
			to_date = Date.today
		end

		@DailyReports = DailyReport.FilterByDate(from_date, to_date).order('date ASC')
	end

	def new
		@daily_report = DailyReport.new
	end

	def edit
		@daily_report = DailyReport.find(params[:id])
	end

	def create
		@daily_report = DailyReport.new(daily_report_params)

		if @daily_report.save
			redirect_to daily_reports_path
		else
			render 'new'
		end
	end

	def update
		@daily_report = DailyReport.find(params[:id])
		
		if @daily_report.update(daily_report_params)
			redirect_to daily_reports_path
		else
			render 'edit'
		end
	end

	def destroy
		@daily_report = DailyReport.find(params[:id])
		@daily_report.destroy
		
		redirect_to daily_reports_path
	end

	def payoutsreport
		@from_date_is_null = true
		@to_date_is_null = true

		if (params[:from_date])
			@from_date_is_null = false
			from_date = params[:from_date]
		else
			from_date = 1.month.ago
		end
		
		if (params[:to_date])
			@to_date_is_null = false
			to_date = params[:to_date]
		else
			to_date = Date.today
		end

		@payouts = DailyReport.FilterByDate(from_date, to_date).joins(:payouts => :payout_category).select(:amount, :pcategory) 
		@payout_groups = @payouts.group(:pcategory).sum(:amount)
		@payouts_sum = @payouts.sum(:amount)
	end

	private
		def daily_report_params
			params.require(:daily_report).permit(:date, :grocery, :fuel, :gift_cards, :credit, :debit, :cash, :commission, :cash_counted, :notes)
		end	
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/views/daily_reports/_form.html.erb
<%= form_for @daily_report do |f| %>

	<% if @daily_report.errors.any? %>
                <div id="error_explanation">
                        <h2>
                                <%= pluralize(@daily_report.errors.count, "error") %> prohibited
                                this report from being saved:
                        </h2>
                        <ul>
                                <% @daily_report.errors.full_messages.each do |msg| %>
                                        <li><%= msg %></li>
                                <% end %>
                        </ul>
                </div>
        <% end %>

        <p>
                <%= f.label :date %><br>
                <%= f.date_select :date, default: Date.today %>
        </p>

        <p>
                <%= f.label :grocery %><br>
                <%= f.number_field :grocery, :class => 'text_field', :step => 'any' %>
        </p>
	
	<p>
                <%= f.label :fuel %><br>
                <%= f.number_field :fuel, :class => 'text_field', :step => 'any' %>
        </p>

	</p>
                <%= f.label :gift_cards %><br>
                <%= f.number_field :gift_cards, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :credit %><br>
                <%= f.number_field :credit, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :debit %><br>
                <%= f.number_field :debit, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :cash %><br>
                <%= f.number_field :cash, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :cash_counted %><br>
                <%= f.number_field :cash_counted, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :commission %><br>
                <%= f.number_field :commission, :class => 'text_field', :step => 'any' %>
        </p>

	<p>
                <%= f.label :notes %><br>
                <%= f.text_field :notes %>
        </p>

        <p>
                <%= f.submit %>
        </p>

<% end %>

app/views/daily_reports/edit.html.erb
<h1>Edit Report</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/index.html.erb
<%= javascript_include_tag "/javascripts/daily_reports_index" %>

<h1>List of daily reports</h1>

<%= link_to 'New Report', new_daily_report_path %>

<%= form_tag daily_reports_path, :method => 'get' do %>
	<p>
		<%= label_tag "From Date: " %>

                <% if @from_date_is_null == true %>
                        <%= date_field_tag :from_date, 2.weeks.ago.to_date %>
                <% else %>
                        <%= date_field_tag :from_date, params[:from_date] %>
                <% end %>


                <%= label_tag "To Date: " %>

                <% if @to_date_is_null == true %>
                        <%= date_field_tag :to_date, Date.today %>
                <% else %>
                        <%= date_field_tag :to_date, params[:to_date] %>
                <% end %>

                <%= submit_tag "Filter", :name => nil %>
	</p>
<% end %>

<p>
	Average sales($)/day for this period: <b><u><%= number_to_currency(@DailyReports.average(:grocery)) %></u></b>
</p>

<table id="reports_table" border="1">
	<tr>
		<th>Date</th>
		<th width="4%"</th>
		<th>Grocery</th>
		<th>Fuel</th>
		<th>Gift Cards</th>
		<th>Total</th>
		<th width="4%"</th>
		<th>Credit</th>
		<th>Debit</th>
		<th>Cash</th>
		<th>Total</th>
		<th width="4%"></th>
		<th>Expected Debit</th>
		<th>Actual Debit</th>
		<th width="4%"></th>
		<th>Payouts</th>
		<th>Cash Expected</th>
		<th>Cash Counted</th>
		<th>Cash Deposited</th>
		<th width="4%"></th>
		<th>Notes</th>
		<th colspan="5"></th>
	<tr>

	<% @DailyReports.each do |dailyreport| %>
		<% @total_payouts = dailyreport.payouts.sum(:amount) %>
		<tr align="right">
			<td><%= dailyreport.date %></td>
			<td></td>
			<td><%= number_to_currency(dailyreport.grocery) %></td>
			<td><%= number_to_currency(dailyreport.fuel) %></td>
			<td><%= number_to_currency(dailyreport.gift_cards) %></td>
			<td id="id_TotalSales"><b><%= number_to_currency(dailyreport.grocery + dailyreport.fuel + dailyreport.gift_cards) %></b></td>
			<td></td>
			<td><%= number_to_currency(dailyreport.credit) %></td>
			<td><%= number_to_currency(dailyreport.debit) %></td>
			<td><%= number_to_currency(dailyreport.cash) %></td>
			<td id="id_TotalReceipts"><b><%= number_to_currency(dailyreport.credit + dailyreport.debit + dailyreport.cash) %></b></td>
			<td></td>
			<td id="id_ExpectedDebit"><%= number_to_currency((dailyreport.fuel + dailyreport.gift_cards - dailyreport.credit - dailyreport.debit) - dailyreport.commission) %></td>
			<td id="id_ActualDebit"><%= number_to_currency(dailyreport.transactions.joins(:entry_category).where(entry_categories: { category: 'SMO Withdrawal' }).sum(:amount))%></td>
			<td></td>
			<td><%= number_to_currency(@total_payouts) %></td>
			<td id="id_ExpectedCash"><%= number_to_currency(dailyreport.cash - @total_payouts) %></td>
			<td id="id_CountedCash"><%= number_to_currency(dailyreport.cash_counted) %></td>
			<td id="id_CashDeposited"><%= number_to_currency(dailyreport.transactions.joins(:entry_category).where(entry_categories: { category: 'Daily Deposit' }).sum(:amount)) %></td>
			<td></td>
			<td><%= dailyreport.notes %></td>
			<td><%= link_to 'Edit', edit_daily_report_path(dailyreport) %></td>
			<td><%= link_to 'Payouts', daily_report_payouts_path(dailyreport) %></td>
			<td><%= link_to 'Deposits', daily_report_deposits_path(dailyreport) %></td>
			<td><%= link_to 'SMO', daily_report_smowithdrawals_path(dailyreport) %></td>
			<td><%= link_to 'Delete', daily_report_path(dailyreport),
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Back to home', root_path %>

app/views/daily_reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/payoutsreport.html.erb
<h1>Payouts Summary</h1>

<%= form_tag payoutsreport_daily_reports_path, :method => 'get' do %>
	<p>
		<%= label_tag "From Date: " %>
		
		<% if @from_date_is_null == true %>
			<%= date_field_tag :from_date, 1.month.ago.to_date %>
		<% else %>
			<%= date_field_tag :from_date, params[:from_date] %>
		<% end %>
		
		<%= label_tag "To Date: " %>
		
		<% if @to_date_is_null == true %>
			<%= date_field_tag :to_date, Date.today %>
		<% else %>
			<%= date_field_tag :to_date, params[:to_date] %>
		<% end %>

		<%= submit_tag "Report", :name => nil %>
	</p>
<% end %>

<table>
	
	<tr><td><h2>Payouts</h2></td></tr>

	<tr>
		<th>Category</th>
		<th>Amount</th>
	</tr>

	<% @payout_groups.each do |payout_group| %>
		<tr>
			<td><%= payout_group[0] %></td>
			<td align="right"><%= number_to_currency(payout_group[1]) %></td>	
		</tr>	
	<% end %>

	<tr>
		<td><b>Total</b></td>
		<td align="right"><b><%= number_to_currency(@payouts_sum) %></b></td>
	</tr>
</table>

<%= link_to 'Back to home', root_path %>